services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      # RTSP
      - "8554:8554"
      # RTMP
      - "1935:1935"
      # HLS
      - "8888:8888"
      # API
      - "9997:9997"
      # WebRTC
      - "8889:8889/udp"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml  # Custom configuration